/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as AuthRouteImport } from "./pages/auth/route"
import { Route as IndexImport } from "./pages/index"
import { Route as WorkspacesWorkspaceIdSettingsImport } from "./pages/workspaces.$workspaceId.settings"

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesWorkspaceIdSettingsRoute =
  WorkspacesWorkspaceIdSettingsImport.update({
    path: "/workspaces/$workspaceId/settings",
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/auth": {
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    "/workspaces/$workspaceId/settings": {
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRouteRoute,
  WorkspacesWorkspaceIdSettingsRoute,
])

/* prettier-ignore-end */
